version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: microseguros-dynamoDB
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]